apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: grapes-project
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: config_db
            - name: POSTGRES_USER
              value: <login>
            - name: POSTGRES_PASSWORD
              value: <password>
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: postgres-init-scripts
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-init-scripts
          configMap:
            name: postgres-init-scripts
        - name: postgres-data
          emptyDir: {}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: grapes-project

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: grapes-project
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
