spring.datasource.url=jdbc:postgresql://localhost:5432/accessService
spring.datasource.username=postgres
spring.datasource.password=Tienmanh2001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
