## Requirements ##

Python 3.10 or higher.

---

## KWIC ##

Implemented solution of the Key Word in Context problem using the "Pipes and Filters" method.

** Expected Result: **

output generated by a  filters makes it easy to analyze the keyword "winter" in its various contexts within the text

---

## 8 Queens ##

Implemented solution of the 8 Queens problem using the "Pipes and Filters" method.

**Expected Result:**

The program will output all found solutions to the "8 Queens" problem.

